use RecipeShopper
go
insert into ingredient (description) values ('Brown Rice')
insert into ingredient (description) values ('Diced Tomatoes')
insert into ingredient (description) values ('Black Beans')
insert into ingredient (description) values ('Corn')
insert into ingredient (description) values ('Edamame')
insert into ingredient (description) values ('Couscous')
insert into ingredient (description) values ('Shrimp')
insert into ingredient (description) values ('Mayonnaise')
insert into ingredient (description) values ('Paprika')
insert into ingredient (description) values ('Corn Kernels')
insert into ingredient (description) values ('Grape Tomatoes')
insert into ingredient (description) values ('Fresh Pasta')

insert into AmountType (description) values ('teaspoon')
insert into AmountType (description) values ('drops')
insert into AmountType (description) values ('dash')
insert into AmountType (description) values ('pinch')
insert into AmountType (description) values ('tablespoon')
insert into AmountType (description) values ('cup')
insert into AmountType (description) values ('ounces')
insert into AmountType (description) values ('grams')
insert into AmountType (description) values ('ml')
insert into AmountType (description) values ('pounds')
insert into AmountType (description) values ('gallons')
insert into AmountType (description) values ('liters')